auth:
  build: ./auth-service/
  # volumes:
  #   - "auth-service/:/src/app"
  ports:
    - "3000:8080"
  env_file: .env
customer:
  build: ./customer-service/
  # volumes:
  #   - "customer-service/:/src/app"
  ports:
    - "3001:8080"
  env_file: .env
product:
  build: ./product-service/
  # volumes:
  #   - "product-service/:/src/app"
  ports:
    - "3002:8080"
  env_file: .env
transaction:
  build: ./transaction-service/
  # volumes:
  #   - "transaction-service/:/src/app"
  ports:
    - "3003:8080"
  env_file: .env
