auth:
  build: ./auth-service/
  ports:
    - "3000:8080"
  env_file: .env
  environment:
    - SERVICENAME=auth-service
customer:
  build: ./customer-service/
  ports:
    - "3001:8080"
  env_file: .env
  environment:
    - SERVICENAME=customer-service
product:
  build: ./product-service/
  ports:
    - "3002:8080"
  env_file: .env
  environment:
    - SERVICENAME=product-service
transaction:
  build: ./transaction-service/
  ports:
    - "3003:8080"
  env_file: .env
  environment:
    - SERVICENAME=transaction-service
